export const RECEIVE_BOOKS = 'RECEIVE_BOOKS'
export const RECEIVE_BOOK = 'RECEIVE_BOOK'
export const CLEAR_BOOK = 'CLEAR_BOOK'

export const ADD_NOTIFICATION = "ADD_NOTIFICATION"
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION"
